### ISSUE TITLE
Tests failing for repo

### ISSUE THREAD

**Issue by SudShekhar** [pinax/pinax-messages#20]
I tried to run the tests both via `detox` and `python runtests.py`. The following two tests were failing 

======================================================================
    ERROR: test_urls (pinax.messages.tests.tests.TestMessageViews)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/sshekh1/.virtualenvs/indoclinic/src/master/pinax/messages/tests/tests.py", line 170, in test_urls
        self.assertEqual(reverse("message_create", args=[10]), "/create/10/")
      File "/Users/sshekh1/.virtualenvs/indoclinic/lib/python2.7/site-packages/django/core/urlresolvers.py", line 600, in reverse
        return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
      File "/Users/sshekh1/.virtualenvs/indoclinic/lib/python2.7/site-packages/django/core/urlresolvers.py", line 448, in _reverse_with_prefix
        self._populate()
      File "/Users/sshekh1/.virtualenvs/indoclinic/lib/python2.7/site-packages/django/core/urlresolvers.py", line 306, in _populate
        p_pattern = pattern.regex.pattern
    AttributeError: 'tuple' object has no attribute 'regex'

    ======================================================================
    FAIL: test_create_message (pinax.messages.tests.tests.TestMessageViews)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/sshekh1/.virtualenvs/indoclinic/src/master/pinax/messages/tests/tests.py", line 115, in test_create_message
        with self.login("brosner", "abc123"):
      File "/Users/sshekh1/.virtualenvs/indoclinic/src/master/pinax/messages/tests/tests.py", line 40, in login
        return login(self, user, password)
      File "/Users/sshekh1/.virtualenvs/indoclinic/src/master/pinax/messages/tests/tests.py", line 20, in __init__
        "login with username=%r, password=%r failed" % (user, password)
    AssertionError: login with username='brosner', password='abc123' failed

    ----------------------------------------------------------------------

**Comment by ossanna16** [comment]
@SudShekhar Is that an issue with `pinax-messages` itself or with your local setup? Feel free to mention this in Slack and someone will be able to help you. Thank you :)

**Comment by grahamu** [comment]
@SudShekhar we just updated pinax-messages and all tests now pass. Thanks very much for your report!
