### ISSUE TITLE
Problem with importing module messageWebsite

### ISSUE THREAD

**Issue by YathishReddy** [pinax/pinax-messages#34]
ImportError: No module named messagesWebsite

This was the error I got when I trying to run manage.py migrate, after following the installation steps of pinax-messages properly. Can I get the fix for this.

**Comment by paltman** [comment]
@YathishReddy can you share the full stack trace?

**Comment by YathishReddy** [comment]
```
(NCC) yathish@KingSparrow:~/Projects/NCC_Website/Website$ pip install -r requirements.txt --upgrade
Requirement already up-to-date: django-user-accounts==1.3.1 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: pinax-webanalytics==2.0.4 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: pinax-eventlog==1.1.2 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: Django==1.9.8 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: pinax-theme-bootstrap==7.10.1 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: pinax-messages in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: pytz>=2015.6 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from django-user-accounts==1.3.1->-r requirements.txt (line 1))
Requirement already up-to-date: django-appconf>=1.0.1 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from django-user-accounts==1.3.1->-r requirements.txt (line 1))
Requirement already up-to-date: jsonfield>=1.0.3 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from pinax-eventlog==1.1.2->-r requirements.txt (line 3))
Requirement already up-to-date: django-bootstrap-form>=3.0.0 in /home/yathish/Projects/NCC_Website/NCC/lib/python2.7/site-packages (from pinax-theme-bootstrap==7.10.1->-r requirements.txt (line 6))
(NCC) yathish@KingSparrow:~/Projects/NCC_Website/Website$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/yathish/Projects/NCC_Website/NCC/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/yathish/Projects/NCC_Website/NCC/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/yathish/Projects/NCC_Website/NCC/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/yathish/Projects/NCC_Website/NCC/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/yathish/Projects/NCC_Website/NCC/local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named messagesWebsite
```

**Comment by paltman** [comment]
I think you are missing a comma in your projects settings.py INSTALLED_APPS after "pinax.messages".

**Comment by YathishReddy** [comment]
thank you, :D @paltman
